### ISSUE TITLE
Need to be able to choose multiple category groups.

### ISSUE THREAD

**Issue by wjthomas9** [NAlbuquerque/Category-Field-for-EE#4]
I need to be able to choose cateogries from multiple category groups. Is this possible?

**Comment by NAlbuquerque** [comment]
Each Category Field can hold only a single category group. I've thought of adding this in the past but it would create some usability issues surrounding the edit controls.

**Comment by wjthomas9** [comment]
I’m happy to help test the usability issues. We’re all power users here, so I don’t think it would be that complex. The interface for this add-on is good enough and is not uneasy to use. I would use it, but I’m getting some PHP errors: http://devot-ee.com/add-ons/wb-category-select

On March 5, 2014 at 5:52:06 PM, Nuno Albuquerque (notifications@github.com) wrote:

Each Category Field can hold only a single category group. I've thought of adding this in the past but it would create some usability issues surrounding the edit controls.

**Comment by NAlbuquerque** [comment]
I meant usability for entry authors when using the Category Field controls on the publish form. For example, the Edit link opens the edit modal. We could easily change that to Edit: My Cat Group1, My Cat Group2, etc. This would create some frustration for users trying to edit the categories since they wouldn't know exactly what group the listed categories belong to. We'd also run into issues regarding display order of the merged categories. Do we adhere to a specific groups order preferences? Or just list everything in alpha order? It's nothing major but will require some thought to implement properly. I'm sure there are a few more edge cases that I've thought about that kept me from actually implementing this... oh and the time to do so is hard to find also :)

**Comment by wjthomas9** [comment]
I see. What I really actually looking for was sort of a preferences screen, where I as the admin could choose _multiple_ category groups to allow that field to display child categories for. The user would still only be choosing a single category from a drop down. They would not have access to the module where you can choose which category groups area allowed to flow into the field.

Hopefully Solspace fixes Primary Category. http://www.solspace.com/software/detail/primary_category/ That’s really what I’m after here. 

Yours would allow me to do it, but it only lets me show categories from one category group. No worries though . For what it is it works great.

On March 5, 2014 at 6:05:36 PM, Nuno Albuquerque (notifications@github.com) wrote:

I meant usability for entry authors when using the Category Field controls on the publish form. For example, the Edit link opens the edit modal. We could easily change that to Edit: My Cat Group1, My Cat Group2, etc. This would create some frustration for users trying to edit the categories since they wouldn't know exactly what group the listed categories belong to. We'd also run into issues regarding display order of the merged categories. Do we adhere to a specific groups order preferences? Or just list everything in alpha order? It's nothing major but will require some thought to implement properly. I'm sure there are a few more edge cases that I've thought about that kept me from actually implementing this... oh and the time to do so is hard to find also :)

**Comment by NAlbuquerque** [comment]
Yep, no worries. If I have time in the future I'll add that in. For now I think the Solspace plugin should do the trick for your. I think I saw a tweet from them that EE 2.8 compatibility is coming in the next few weeks. Good luck!

**Comment by wjthomas9** [comment]
Thanks!

On March 5, 2014 at 6:20:26 PM, Nuno Albuquerque (notifications@github.com) wrote:

Yep, no worries. If I have time in the future I'll add that in. For now I think the Solspace plugin should do the trick for your. I think I saw a tweet from them that EE 2.8 compatibility is coming in the next few weeks. Good luck!
